services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend
      dockerfile: DockerFile
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_USER=youruser
      - DB_PASSWORD=yourpassword
      - DB_NAME=yourdb
      - DB_HOST=db
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db-data:
