FROM golang:1.22 AS builder

# RUN apt-get update && apt-get install -y bash

# Build the go binary
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o main 

EXPOSE 8080
CMD ["sh", "-c", "./main"]